- name: Install web server on the hosts
  hosts: all
  tasks:

    - name: install web server on the hosts
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: restart the web server on the target host
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: restarted

    - name: create a file
      ansible.builtin.file:
        name: /var/www/html/index.html
        owner: awx
        group: awx
        mode: 0644

    - name: copy the content.
      lineinfile:
        path: /var/www/html
        line: "{{ web_message }}"

      
      
